site_name: Patagonia Warriors
site_url: https://patagoniawarriors.github.io
theme:
  logo: cosas/pw.ico
  favicon: cosas/pwficon.png
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a las preferencias del sistema

nav:
  - Inicio: index.md
  - Informacion:
    - Reglas: info/reglas.md
    - Servidores: info/servidores.md
  - Donaciones:
    - Donar al Server: donaciones/donar.md
    - Beneficios del Donador: donaciones/beneficios.md
    - TOP 5 Donadores: donaciones/top5.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WPJuTwwCTD
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/patagoniawarriors
    - icon: fontawesome/brands/github
      link: https://github.com/patagoniawarriors/docs

copyright: |
    &copy Copyright 2024 Patagionia Warriors - hecho por stereosound. Esta documentación esta basada en el trabajo de Servilive: https://github.com/servilive/docs
    Si creas un fork de este repositorio, por favor dale credito al repositorio original siguiendo la licencia del mismo.
